name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Zip files
        run: |
          zip plugin-release.zip main.js manifest.json styles.css

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css plugin-release.zip

      - name: Commit to releases branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Stash changes to prevent conflicts when switching branches
          git stash
          
          git checkout releases
          git add -f main.js manifest.json styles.css
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Release ${{ github.ref }}"
            git push origin releases
          fi
          
          # No need to apply the stashed changes, so we can drop them
          git stash drop
